### ISSUE TITLE
Problem with launch on Ubuntu

### ISSUE THREAD

**Issue by Disinterpreter** [vsTerminus/Mojo-Discord#2]
I saw problem with launch on Ubuntu 16.04 and perl 5.22

`Can't use an undefined value as a HASH reference at /usr/local/share/perl/5.22.1/Mojo/Discord/Gateway.pm line 126.`

**Comment by Disinterpreter** [comment]
Closed. Problem in availability IO::Socket::SSL.

**Comment by vsTerminus** [comment]
Ok - Glad you figured it out. Sorry I wasn't able to respond sooner.
