### ISSUE TITLE
Gateway Intents

### ISSUE THREAD

**Issue by incognico** [vsTerminus/Mojo-Discord#25]
https://discord.com/developers/docs/topics/gateway#gateway-intents

Sooner or later this has to be implemented: `Intents are optionally supported on the v6 gateway. They will become mandatory in a future gateway version.`

https://ziad87.net/intents/

**Comment by incognico** [comment]
I will look into this.

**Comment by vsTerminus** [comment]
This is implemented as of https://github.com/vsTerminus/Mojo-Discord/commit/37b3fad3219d0817bd2743571692eb36354a2999 

Library is now using Gateway v8 and is requesting all intents it is capable of using.
