### ISSUE TITLE
Feature Request: Wiki command

### ISSUE THREAD

**Issue by hatchh** [vsTerminus/Mojo-Discord#3]
Essentially a command that works like the Urban Dictionary except that it brings up the first Wikipedia

For example !wiki Thomas Edision would bring up a link to Thomas Edision's wikipedia page

**Comment by vsTerminus** [comment]
This repo is for the library that connects to Discord and implements the API.

This request should actually be posted over here: https://github.com/vsTerminus/Goose/issues

I'll leave it for you to post so you get the notifications.
