### ISSUE TITLE
Can i edit or delete message?

### ISSUE THREAD

**Issue by Disinterpreter** [vsTerminus/Mojo-Discord#4]
subj

**Comment by vsTerminus** [comment]
Not currently, but I'll consider this a feature request.

**Comment by Disinterpreter** [comment]
Ok, don't drop this project 🗡 i write bots on it.

**Comment by vsTerminus** [comment]
No plans to drop it, just haven't had any free time lately to work on it. Trying to find some time this week.

**Comment by Disinterpreter** [comment]
#5

**Comment by vsTerminus** [comment]
I merged this last year but my repo wasn't in a very good state to push to github. I've cleaned it up and can now push this commit.
